// ENTERTAINMENT PRODUCTION BY FENNIKS ALL RIGHTS RESERVED
// COPYRIGHT @ 2014 ALL RIGHTS RESERVED
<?php require_once('game/config/config.php'); ?>


<a href='logowanie.php'>Logowanie
// ENTERTAINMENT PRODUCTION BY FENNIKS ALL RIGHTS RESERVED
// COPYRIGHT @ 2014 ALL RIGHTS RESERVED