// ENTERTAINMENT PRODUCTION BY FENNIKS ALL RIGHTS RESERVED
// COPYRIGHT @ 2014 ALL RIGHTS RESERVED
<?php
$poz_x = ((-$player['x']) * 32) + 240;
$poz_y = ((-$player['y']) * 32) + 240;
?>
// ENTERTAINMENT PRODUCTION BY FENNIKS ALL RIGHTS RESERVED
// COPYRIGHT @ 2014 ALL RIGHTS RESERVED